// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcw7OdltAd0O-v3_LRhxFR3Px2AKdNQ3Q',
    appId: '1:358560039012:web:479cb4169993a1ac1c9f71',
    messagingSenderId: '358560039012',
    projectId: 'todoapp-47a4b',
    authDomain: 'todoapp-47a4b.firebaseapp.com',
    storageBucket: 'todoapp-47a4b.appspot.com',
    measurementId: 'G-BKCCRWED65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIZCXzowOgyzp3Lf5D7UIYF5ZFbvRA6M',
    appId: '1:358560039012:android:7794470b68c6ae1f1c9f71',
    messagingSenderId: '358560039012',
    projectId: 'todoapp-47a4b',
    storageBucket: 'todoapp-47a4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5H9AnKdcKTO62cWm5F00PK4TmEEYoQA',
    appId: '1:358560039012:ios:da884048f84981a41c9f71',
    messagingSenderId: '358560039012',
    projectId: 'todoapp-47a4b',
    storageBucket: 'todoapp-47a4b.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5H9AnKdcKTO62cWm5F00PK4TmEEYoQA',
    appId: '1:358560039012:ios:889dfa567ab2f92d1c9f71',
    messagingSenderId: '358560039012',
    projectId: 'todoapp-47a4b',
    storageBucket: 'todoapp-47a4b.appspot.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
